production:
  periodic_cleanup:
    class: TransactionFeesImportJob
    queue: background
    schedule: every day at 12:00am

  spots_import_job:
    class: SpotsImportJob
    queue: background
    args: ["usd", { seed: false }]
    priority: 1
    schedule: every 3 minutes

  refresh_hodl_hong_baos_job:
    class: RefreshHodlHongBaosJob
    queue: background
    schedule: every day at 2:00am